[project]
name = "kaloriekassen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "browser-cookie3>=0.20.1",
    "bs4>=0.0.2",
    "google-auth-oauthlib>=1.4.0",
    "google-oauth2-tool>=0.0.3",
    "lxml>=5.4.0",
    "myfitnesspal>=2.1.2",
    "pandas>=3.0.3",
    "playwright>=1.59.0",
    "psycopg2-binary>=2.9.12",
    "pytest>=9.0.3",
    "python-dotenv>=1.2.2",
    "requests-toolbelt>=1.0.0",
    "rich>=12.6.0",
    "ruff>=0.15.13",
]

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"


[project.scripts]
kaloriekassen = "kaloriekassen.cli:main"

[tool.pytest.ini_options]
markers = [
    "integration: tests that call external services",
]
