### File Variables for the Codelab
import setttings


@client_id = settings.GOOGLE_CLIENT_ID
@secret = settings.GOOGLE_CLIENT_SECRET
@redirect_uri = settings.GOOGLE_REDIRECT_URI
@auth_kode = setttings.GOOGLE_AUTH_CODE
@accessToken={{user.response.body.access_token}}
@refreshToken={{user.response.body.refresh_token}}

# @name user
POST https://oauth2.googleapis.com/token
Content-Type: application/x-www-form-urlencoded

code={{auth_kode}}&client_id={{client_id}}&client_secret={{secret}}&redirect_uri={{redirect_uri}}&grant_type=authorization_code



# for at hente en ny auth_kode med client_id og redirect_uri, skal du åbne nedenstående URL i en browser og logge ind med den Google-konto, du vil bruge til codelabben. Når du har givet tilladelse, vil du blive omdirigeret til redirect_uri'en, og auth_koden vil være synlig i URL'en som en query parameter.
# 

https://accounts.google.com/o/oauth2/v2/auth?client_id=client-id&redirect_uri=https://www.google.com&response_type=code&access_type=offline&scope=https://www.googleapis.com/auth/googlehealth.activity_and_fitness.readonly

# bemærk at det slutter med scope, andre scopes kan findes her https://developers.google.com/health/scopes#available_scopes